### ISSUE TITLE
【关于训练复现的错误】

### ISSUE THREAD

**Issue by inaomIIsfarell** [benedictstar/Joint-VAD#1]
您好！首先对您出色的工作表示敬佩。

我在使用您开源的代码复现模型在``ShanghaiTech``上训练时中发现报错(如下图)
![error_log](https://github.com/user-attachments/assets/c03739f6-4dca-4648-b64b-a115f0abf520)

经定位，发现 **[Occ/utils/training_scoring_utils.py, line92](https://github.com/benedictstar/Joint-VAD/blob/641a31c21a52e5285888c68e8e742aafb6a2a263/Occ/utils/training_scoring_utils.py#L92)** 处，**[video_length即data/weakly_ShanghaiTech/shanghai-num.npy](https://github.com/benedictstar/Joint-VAD/blob/main/data/weakly_ShanghaiTech/shanghai-num.npy)** 不存在``key``为 **01_001** 的item，而导致 **data/weakly_ShanghaiTech/pose/train/pose** 中以``_alphapose_tracked_person.json``结尾的内容与其不匹配。

且 **[data/weakly_ShanghaiTech/shanghai-num.npy](https://github.com/benedictstar/Joint-VAD/blob/main/data/weakly_ShanghaiTech/shanghai-num.npy)** 中共有 **238** 个键值对（应该是``ShanghaiTech``上**训练集**的长度？ ）。而从您提供的数据中  **[data/weakly_ShanghaiTech/pose/train/pose](https://drive.google.com/file/d/1o9h3Kh6zovW4FIHpNBGnYIRSbGCu-qPt/view)** 中下载到的以``_alphapose_tracked_person.json``结尾的文件共有 **330** 个，这 **330** 个文件又代表什么呢？我该如何修改呢？

期待您的回复，谢谢！

**Comment by benedictstar** [comment]
Hi! Thank you for your attention for our work.
The pose data from this [link](https://drive.google.com/file/d/1o9h3Kh6zovW4FIHpNBGnYIRSbGCu-qPt/view?usp=sharing) in STG-NF is the dataset partitioned for OCC mode, you need to repartition them for training or testing in unsupervised mode. For convenience, we update the link in Readme.md and now the data from the new link can be used directly for training or testing in our repository.

**Comment by inaomIIsfarell** [comment]
> Hi! Thank you for your attention for our work. The pose data from this [link](https://drive.google.com/file/d/1o9h3Kh6zovW4FIHpNBGnYIRSbGCu-qPt/view?usp=sharing) in STG-NF is the dataset partitioned for OCC mode, you need to repartition them for training or testing in unsupervised mode. For convenience, we update the link in Readme.md and now the data from the new link can be used directly for training or testing in our repository.

thank you! it was solved
